### ISSUE TITLE
Non-latin keymaps in label-mode

### ISSUE THREAD

**Issue by teu5us** [justinmk/vim-sneak#246]
I use vim (neovim) with a russian keymap. Unlike easymotion or vim-snipe, vim-sneak supports keymap when one is used. However, with label-mode active I cannot jump to label when my keymap is activated

**Comment by justinmk** [comment]
You can change the labels to match your keymap: https://github.com/justinmk/vim-sneak/blob/24e6c3f4cd6004e2b44e4022dee0260aba6132aa/doc/sneak.txt#L325

Example:

    let g:sneak#target_labels="асдфгхйкл'зьцжбнм,./явертыуипо"

**Note:** I found a bug with multibyte labels, which should be fixed in the latest version.

You could instead disable the keymap during sneak-mode (`:help sneak-events`) ... though of course that of course defeats the purpose of 'keymap' , but just mentioning it for reference:

    :autocmd User SneakEnter set keymap=
    :autocmd User SneakLeave set keymap=russian-yawerty

**Comment by teu5us** [comment]
Changing labels to russian completely breaks jumping when the keymap is not active. And disabling the keymap breaks search in russian. I guess I can go with something like this though:
```
  function! SetLabels()
    if &iminsert
      let g:sneak#target_labels = "яжнладчхЖНГОЗЛАДЩЬЧ,Х0"
    else
      let g:sneak#target_labels = ";sftunq/SFGHLTUNRMQZ?0"
    endif
  endfunction
  au User SneakEnter call SetLabels()
```

Also, still having problems with multibyte labels
![pic-full-200106-1346-09](https://user-images.githubusercontent.com/42467493/71803651-8f3dc980-308b-11ea-9b62-8c36d4338b7a.png)
![pic-full-200106-1346-38](https://user-images.githubusercontent.com/42467493/71803659-9369e700-308b-11ea-9ff2-aa46e0b251d4.png)

**Comment by teu5us** [comment]
Saw [this](https://github.com/justinmk/vim-sneak/issues/232#issuecomment-423802591), but I can only go to the next group of labels, not backward.

**Comment by justinmk** [comment]
> Also, still having problems with multibyte labels

? screenshot looks fine to me.

> Changing labels to russian completely breaks jumping when the keymap is not active. And disabling the keymap breaks search in russian. I guess I can go with something like this though:

Not sure what you expect? Can't have it both ways. Yes, changing labels on `SneakEnter` event as you showed seems pretty reasonable.

**Comment by teu5us** [comment]
@justinmk 
Guess I misunderstood what you said about multibyte labels. Still, when I get the next portion of matches labelled using `<Tab>` I can't return to the previous one with `<S-Tab>` or `<BS>`. Sure I can live without it, but it seems to me that something isn't working. I tried changing the keys in label.vim, but going back just does not work.

**Comment by justinmk** [comment]
> when I get the next portion of matches labelled using `<Tab>` I can't return to the previous one with `<S-Tab>` or `<BS>`.

works for me. Tested this config and text:

```
let g:sneak#label = 1   
set keymap=russian-yawerty                                                     
let g:sneak#target_labels = 'асдфгхйк;л'
function! SetLabels()    
  if &iminsert                                                             
    let g:sneak#target_labels = "яжнладчхЖНГОЗЛАДЩЬЧ,Х0"   
  else                                                        
    let g:sneak#target_labels = ";sftunq/SFGHLTUNRMQZ?0"
  endif                     
endfunction                                                    
au User SneakEnter call SetLabels()                                                                                                       
                          
" яверуиииииопасдфкйл;гхзьасдфкйл;гхзьасдфкйл;гхзьцжбнм,,,,,яверуиииииопасдфкйл;гхзьцжбнм,,,,,
" яверуиииииопасдфкйл;гхзьасдфкйл;гхзьасдфкйл;гхзьцжбнм,,,,,яверуиииииопасдфкйл;гхзьцжбнм,,,,,
" яверуиииииопасдфкйл;гхзьасдфкйл;гхзьасдфкйл;гхзьцжбнм,,,,,яверуиииииопасдфкйл;гхзьцжбнм,,,,,
" яверуиииииопасдфкйл;гхзьасдфкйл;гхзьасдфкйл;гхзьцжбнм,,,,,яверуиииииопасдфкйл;гхзьцжбнм,,,,,
" яверуиииииопасдфкйл;гхзьасдфкйл;гхзьасдфкйл;гхзьцжбнм,,,,,яверуиииииопасдфкйл;гхзьцжбнм,,,,,
" яверуиииииопасдфкйл;гхзьасдфкйл;гхзьасдфкйл;гхзьцжбнм,,,,,яверуиииииопасдфкйл;гхзьцжбнм,,,,,
" яверуиииииопасдфкйл;гхзьасдфкйл;гхзьасдфкйл;гхзьцжбнм,,,,,яверуиииииопасдфкйл;гхзьцжбнм,,,,,
```

**Comment by teu5us** [comment]
@justinmk 
I can confirm it works with a clean init.vim. It interferes with something in my config then

**Comment by teu5us** [comment]
Found what was causing the issue while rewriting my config. 
regexpengine should not be set to 1
